### ISSUE TITLE
Document: Design suggest roommates group feature

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#196]
Possible option: 
1. Each one (interested or owner) choose the ones he can live with from the interested list.
2. The site display possible groups, several options (based on matching) to the owner for his decision - "close the deal"

**Comment by omrihuller** [comment]
Time estimation: 2 days

**Comment by alonttal** [comment]
Hi Omri,
About option 3 you suggested, how do we know that the top 2 people (for example) are compatibale with one another? it may be that they're compatible with the owner but not with one another. I think that taking the top people is a good solution though.
In addition we need to define in what situation the operation of group construction is occuring, and what technology we use for that.

**Comment by omrihuller** [comment]
Hi Alon,
Thats a good point, I think that if we see that the accuracy is a problem we can combine option 1 and option 3. Meaning we check more possible groups in the top of the list (instead of taking the top group only).

Triggers will be covered in #238 

Regarding technology, could you explain what you mean?
If you mean implementation I'd like to discuss the best way with Or or you.

**Comment by OrAbramovich** [comment]
Another issue I would like to raise - once the owner and/or the users are given a group suggestion by the system they (anyone of them) should have the option to accept / reject it and the system has to response to the feedback i.e - all members of the group and the owner accepted? Close the deal! One person rejected? the option isn't relevant, continue to the following group.
Of course that in order to get the feedback, the users have to be notified somehow - we have to design it as well.

What do you think?

**Comment by omrihuller** [comment]
That's an idea I liked too, if you read in #239 I suggested a "Form group" button that should do exactly what you talked about.
It is under Future since as you mentioned it requires a separate notification system,
but I also think its a necessary feature that fits our goal to simplify the process for the users.

**Comment by omrihuller** [comment]
week 3: should also start implementing

**Comment by omrihuller** [comment]
Following the weekly meeting, searched for an appropriate algorithm or an approximation algorithm.

As we already knew the naive algorithm for finding a clique of size k works in time complexity of O(n^k)

A 3-clique can be found in O(n^2.376) but is using at least O(n^k) memory.
A 4-clique can be approximated in O(n^3)
and larger cliques follow O(n^(1+k/2)) for the approximated version.

In any case, these results are not enough for us and these algorithms are the best known ones.
Meaning we must use heuristics of some sort.

**Comment by omrihuller** [comment]
The chosen design is:
Maintain a sorting of the "liked list" for each user, then try the combinations in descending order.
Any user can ask for a suggested group and the owner can view the groups formed.
Once all participants of a group agree, everyone including the owner are notified.

This closes the design.
