### ISSUE TITLE
Change How Socket Connection Behaves

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#372]
Hi
is it possible to move the sending of the jwt token from the connect phase to the join phase?
I think it's more reasonable and also ease the work on the front-end side.

**Comment by alonttal** [comment]
We shiuld not establish room with the user untill he joins. Of course he will not be able to join if he's not logged in.

**Comment by OrAbramovich** [comment]
The room concept is just another level of abstraction. Once you are connected - all resources have been already allocated and you can communicate with the server. It will not allow him communicate with other users since server will block him but it will allow him to allocate resources on the server and to send messages (as much as he wants) to the server.

**Comment by OrAbramovich** [comment]
As said - room isn't a resource , it's just a level of abstraction (of course it has a cost of an entry in a map,... etc. or something similiar). You can communicate with the server and the server can communicate with you without a room. It also may affect us in the future e.g. in case of using broadcast messages - it will be sent to the unregistered users as well.
You are right that you can overload the server without it but it's another point of failure. But forget the resources and all other things - what's the purpose of allowing it? If unregistered user cannot communicate with the server through sockets why is it more reasonable to allow him establishing the connection?

**Comment by OrAbramovich** [comment]
I think that I miss your point. Lets talk about it tomorrow in the weekly meeting?

**Comment by alonttal** [comment]
we decided to keep it as is.
