### ISSUE TITLE
[Azure] Figure out if to use serverless or load blalancer

### ISSUE THREAD

**Issue by alonttal** [TechnionYearlyProject/Roommates#421]
estimated time: 8 hours

**Comment by OrAbramovich** [comment]
Time estimation: 4 hours.
Due date: 26.05

**Comment by OrAbramovich** [comment]
Hi @Danielohayon ,

What is the status? Due date was yesterday.

**Comment by omrihuller** [comment]
the strategy for using azure

**Comment by omrihuller** [comment]
estimate: 0.5 hours

**Comment by Danielohayon** [comment]
### Conclusion
After a lot of consideration we have concluded that the best way to go is with load balancing. This is because using serverless computing with Azure functions has it's drawbacks. Such as a need the change our server to be completely stateless which it is not right now, (One example is saving a token for the current connected user). In addition it's mentioned that the latency is a bit higher, while also not having a lot of documentation and support relatively to load balancing. 
In addition as for load balancing it is much more suitable for our current situation. For example, the source IP address of the clients can be seen in the logs of the server which makes it easy to differentiate each of the clients that are connecting to the server. And it automatically deploys server in accordance with our current needs. 

### sources:
[Azure Functions documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-compare-logic-apps-ms-flow-webjobs)
[Azure Load Balancing documentation](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview)
[Serverless computing pros and cons ](https://assist-software.net/blog/pros-and-cons-serverless-computing-faas-comparison-aws-lambda-vs-azure-functions-vs-google)
[Load Balancing pros and cons](https://kemptechnologies.com/au/white-papers/pros-and-cons-of-layer-7-transparency-for-server-load-balancing/)

Time Took: 
4 hours.
