### ISSUE TITLE
Document: Update mid semester POC presentation with UC diagram

### ISSUE THREAD

**Issue by OrAbramovich** [TechnionYearlyProject/Roommates#447]
Update the mid semester POC presentation with UC diagram. The UC diagram should include the pain and the solution provided by Roommates platform.

Follows #425

**Comment by OrAbramovich** [comment]
Time estimation: 1 hour.

**Comment by Danielohayon** [comment]
I was unsure whether we would prefer to show in the presentation the whole Use Case Diagram or just parts of it so i prepared both so we can decide together.
### This is the whole Use Case Diagram:
[Whole Use Case Diagram.pdf](https://github.com/TechnionYearlyProject/Roommates/files/2028925/Use.Cases-5.pdf)
### This is the Use Case Diagram decided into 
[Lonely Dave.pdf](https://github.com/TechnionYearlyProject/Roommates/files/2028933/Lonely.Dave.pdf)
[Already Social Sam.pdf](https://github.com/TechnionYearlyProject/Roommates/files/2028934/Already.Social.Sam.pdf)
[Only owner-2.pdf](https://github.com/TechnionYearlyProject/Roommates/files/2028936/Only.owner-2.pdf)


I personally think that the whole use case diagram is more understandable because you can see every thing together but on the other hand it might have too many details for one slide of the presentation.
I think it would be best if we each weigh in on it here in the issue to decide.
