### ISSUE TITLE
Bug: Entrance date is always set to Thu Jan 01 1970

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#462]
probably due to 0 value returning from the DB

**Comment by idanyadgar** [comment]
The problem is in the apartment publish, it divides the timestamp by 1000 before sending it to the server (didn't find it in the code, but analyzed the network).

**Comment by alonttal** [comment]
hi
I found this line above the calendar tag in the html (commented in the image);
![image](https://user-images.githubusercontent.com/16474068/40419071-cd3b5298-5e8c-11e8-9daa-baa0d4c3d688.png)
since it had a mask it cut the full date in millis.
i remove this line and push to version-1.

fixed.
time: 30 min
