### ISSUE TITLE
Deploy Azure

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#503]
following #421

**Comment by Danielohayon** [comment]
After deciding to use the load balancer options I started reading instructions on how to reply one. 
After consideration I decided to follow the formal one which can be found here: 
[Create a Standard Load Balancer to load balance VMs using the Azure portal](https://docs.microsoft.com/en-us/azure/load-balancer/quickstart-load-balancer-standard-public-portal)

I used my own Azure profile for now and started following the manual and document it simultaneously for feature uses. 
### step 1 - Create a public load balancer
Was to set up a public load balancer system. I named it RoommatesLoadBalancer and gave it a static IP instead of a dynamic one. In addition I set it up in west Europe.

### step 2 - Create backend servers
This step is meant to create a virtual network to house the servers we will set up next. 
I named this virtual network as RoommatesVnet and set it's range of IPs to 10.0.0.0/16. 

### step 3 - Create virtual machines
Now it is time to create the actual virtual machines that will be deployed. So i created the first one naming it RoommatesVM1. Next I set up it's user name to RoommatesAdmin and the password to Roommates2018
Next I selected a virtual machine with SSD and 4GB ram (B1ms)
The DS1_V2 that they recommended to select is 98$ a month and I wasn't sure if we had it or even if we need a very powerful VM to start with so i selected a cheaper one for now.
### step 3.1
Deploy another virtual machine with the name RoommatesVM1 but the same user and password, the same Availability set, the same virtual network, the same subnet and the same NetworkSecurityGroup.
Now I needed to wait for the VMs to be deployed a process that took about 30 minutes.
Meanwhile I continued reading about setting up the load balancer.  

### step 4 - Create NSG rules
In this section, I created NSG rules to allow inbound connections using HTTP and RDP.
I started adding  Inbound security rules to the NetworkSecurityGroup. 
The first rule had these parameters: 
* Service Tag - for Source.
* Internet - for Source service tag
* 80 - for Source port ranges
* \* for Destination port
* TCP - for Protocol
* Allow - for Action
* 1010 for Priority
* RoommatesHTTPRule for name
* Allow HTTP - for description

Next I added a RDP rule to the same NetworkSecurityGroup with these parameters: 
* Service Tag - for Source.
* Internet - for Source service tag
* 3389 - for Destination port ranges
* TCP - for Protocol
* Allow - for Action
* 1020 for Priority
* RoommatesRDPRule for name
* Allow RDP - for description

### Step 5 - Install IIS
In this step I connected to the first virtual machine using a RDP connection. I had set up named RoommatesVM1 and set up its server manager. I went to Add Roles and features and set it up to be a web server (IIS). This included following the windows wizard and installing the necessary components. 
Next we have to repeat the process for RoommatesVM2. 

This is where I had to stop. 
Total time invested in this assignment is 5 hours.
