### ISSUE TITLE
Back-End: when new interested 

### ISSUE THREAD

**Issue by omrihuller** [TechnionYearlyProject/Roommates#505]
basic algorithm for where to put him, top permutations including him

change/add to group schema accordingly

when enough users are interested start forming groups and update DB with the groups
when user is not interested anymore update accordingly

**Comment by omrihuller** [comment]
estimate: 8 hours

**Comment by alonttal** [comment]
Hi @omrihuller ,
can you tell me what are the schemes?

**Comment by omrihuller** [comment]
hi @alonttal 
pushed them now, its an in progress version and we can change it as needed.
the schema is in models/group

**Comment by alonttal** [comment]
@omrihuller 
can you please push it to "closeTheDeal-feature" branch?

**Comment by alonttal** [comment]
@omrihuller 
I merged the closeTheDeal-feature branch with master so we can align

**Comment by omrihuller** [comment]
added subtask #518

**Comment by omrihuller** [comment]
improved the create groups when expressing interest,
added removing groups when removing interest
basic test case for both

this took: 7 hours
total up to here: 11 hours

**Comment by alonttal** [comment]
hi I updated the createGroup function (didn't change functionality)
also, I think that the group object should contain members array (as it does now), but this array should be of objects with the following properties:
_id: the id of the user
status: his current status in the group (accept, decline, pending...)

this should be instead of 2 arrays each containing this 2 values separately.

**Comment by omrihuller** [comment]
@alonttal 
makes sense, will add this to backlog
