### ISSUE TITLE
continue Azure deployment

### ISSUE THREAD

**Issue by chananbental** [TechnionYearlyProject/Roommates#531]
followup on #503 
estimated: 9 hours

first deploy DB and then code

**Comment by alonttal** [comment]
Hi Daniel? how's it going with it?

**Comment by Danielohayon** [comment]
Making progress, I have the servers up and running. But not done yet, Im trying to deploy the database now.

**Comment by Danielohayon** [comment]
## Progress
Continued researching the deployment phase. I had to repeat a lot of the word I had previously done and face a few technical difficulties getting the servers up and running and configuring them to distribute the work between them. 
Now The process I repeated and actually improved upon with a better selection of more sutible vas and a better configuration of SKU IP addresses and that now it's in the common group of Roommates in Azure so every one has access to it. 

The steps I took to get the servers running are: 
### step 1 - Create a public load balancer
Was to set up a public load balancer system. I named it RoommatesLoadBalancer and gave it a static IP instead of a dynamic one. In addition I set it up in west Europe.

### step 2 - Create backend servers
This step is meant to create a virtual network to house the servers we will set up next. 
I named this virtual network as RoommatesVnet and set it's range of IPs to 10.0.0.0/16. 

### step 3 - Create virtual machines
Now it is time to create the actual virtual machines that will be deployed. So i created the first one naming it RoommatesVM1. Next I set up it's user name to RoommatesAdmin and the password to Roommates2018
Next I selected The DS1_V2 that they recommended to which costs 98$ a month even though I wasn't sure if we had it or even if we need a very powerful VM to start with so i selected a cheaper one for now. And selected a standard IP SKU mode. 
### step 3.1
Deploy another virtual machine with the name RoommatesVM1 but the same user and password, the same Availability set, the same virtual network, the same subnet and the same NetworkSecurityGroup.
Now I needed to wait for the VMs to be deployed a process that took about 30 minutes.
Meanwhile I continued reading about setting up the load balancer.  

### step 4 - Create NSG rules
In this section, I created NSG rules to allow inbound connections using HTTP and RDP.
I started adding  Inbound security rules to the NetworkSecurityGroup. 
The first rule had these parameters: 
* Service Tag - for Source.
* Internet - for Source service tag
* 80 - for Source port ranges
* \* for Destination port
* TCP - for Protocol
* Allow - for Action
* 1010 for Priority
* RoommatesHTTPRule for name
* Allow HTTP - for description

Next I added a RDP rule to the same NetworkSecurityGroup with these parameters: 
* Service Tag - for Source.
* Internet - for Source service tag
* 3389 - for Destination port ranges
* TCP - for Protocol
* Allow - for Action
* 1020 for Priority
* RoommatesRDPRule for name
* Allow RDP - for description

### Step 5 - Install IIS
In this step I connected to the first virtual machine using a RDP connection. I had set up named RoommatesVM1 and set up its server manager. I went to Add Roles and features and set it up to be a web server (IIS). This included following the windows wizard and installing the necessary components. 
Next we have to repeat the process for RoommatesVM2. 

### Step 6 - Create load balancer resources
In this section, I configured load balancer settings for a backend address pool and a health probe, and specify load balancer and NAT rules.

### Step 7 - Create a load balancer rule
A load balancer rule is used to define how traffic is distributed to the VMs. I defined the frontend IP configuration for the incoming traffic and the backend IP pool to receive the traffic, along with the required source and destination port. Created a load balancer rule RoommatesLoadBalancerRuleWeb for listening to port 80 in the frontend FrontendLoadBalancer and sending load-balanced network traffic to the backend address pool RoommatesBackEndPool also using port 80.


Total Work Time: 9 hours.
