### ISSUE TITLE
Bug: Weird chat behavior

### ISSUE THREAD

**Issue by idanyadgar** [TechnionYearlyProject/Roommates#617]
Messages sent from A to B appear once from A point of view but are received 4 times at B and are not saved in the DB (on refresh we don't see them).

**Comment by idanyadgar** [comment]
@OrAbramovich I'll need your help here.

**Comment by alonttal** [comment]
hi @idanyadgar 
whats the status for this?

**Comment by idanyadgar** [comment]
@alonttal Same.

**Comment by OrAbramovich** [comment]
Hi @idanyadgar ,

Reproduced on my machine. 

Probably caused by a merge issue - there were 2 handlers for each message. Anyway - added another check (to != current user) - I pushed the changes to private-messaging branch (only).

Can you verify it? (pay attention! checking it on Azure requires a merge with your branch and with the master since the Azure site uses the cloud db that contains new types of notifications, etc. hence - you can get errors with your branch because your back-end is not familiar with those types).

Shabat Shalom.

**Comment by idanyadgar** [comment]
Yes, that was it.
Done.
